# Generated by Django 3.0.8 on 2020-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201105_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
