# Generated by Django 3.0.8 on 2021-02-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_min_order'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='brand_items', to='shop.Brand'),
        ),
    ]
