# Generated by Django 3.0.8 on 2021-02-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_ordersitem_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='brand',
            field=models.IntegerField(default=0),
        ),
    ]
