# Generated by Django 3.0.8 on 2021-02-05 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210205_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
