# Generated by Django 3.0.8 on 2020-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20201222_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.CharField(choices=[('client', 'Client'), ('company', 'Company'), ('admin', 'Admin')], max_length=100),
        ),
    ]
