# Generated by Django 3.0.8 on 2021-02-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_min_order'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrdersItem',
            new_name='OrderItem',
        ),
    ]
